name: eboss_tuonglong
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+2

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.1
  animated_splash_screen: ^1.3.0
  http: ^1.2.2
  shared_preferences: ^2.0.10  # Để lưu trữ thông tin tài khoản trên thiết bị
  intl: ^0.20.2
  flutter_datetime_picker_plus: ^2.2.0
  table_calendar: ^3.2.0
  provider: ^6.1.5
  data_table_2: ^2.5.10
  sqflite: ^2.4.2
  path_provider: ^2.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoiconapp.png" # ← đường dẫn đến icon của bạn
  remove_alpha_ios: true # Thêm dòng này để loại bỏ alpha trên iOS


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/logoTuongLong.png
    - assets/lego_eboss.png
    - assets/abc.png
    - assets/Email.png
    - assets/user-circle.png
    - assets/Phone.png
    - assets/Person.png
    - assets/Perm contact calendar.png
    - assets/Calendar view day.png
    - assets/Logout.png
    - assets/Icon_Illustration.png
    - assets/productivity.png
    - assets/schedule.png
    - assets/home.png
    - assets/copywriting.png
    - assets/profile.png
    - assets/userinfo_image.png
    - assets/userinfo_avatar.png
    - assets/icon_QR.png
    - assets/search_icon.png
    - assets/default_item_image.png
    - assets/edit.png   
    - assets/delete.png
    - assets/box.png
    - assets/img_tuonglong.png
    - assets/iconquanlykho.png
    - assets/iconthongke.png
    - assets/icon_theodoitiendomau.png